apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.web.app }}
  name: {{ .Values.web.name }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.web.app }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.web.app }}
    spec:
      containers:
      - name: {{ .Values.web.name }}
        image: {{ .Values.web.image }}
        imagePullPolicy: {{ .Values.web.imagePullPolicy }}
        ports:
          - containerPort: {{ .Values.web.containerPort }}
