web:
  name: web-deploy
  app: web
  replicas: 6
  image: kienbt/vietnam:v0.3
  imagePullPolicy: Always
  containerPort: 8080
service: 
  name: ps-nodeport
  type: NodePort
  port: 80
  targetPort: 8080
  NodePort: 31112
  protocol: TCP
  app: web
